formulas:
  - 'coreutils'
  - 'curl'
  - 'git'
  - 'bash'
  - 'gnupg2'
  - 'gawk'
  - 'libyaml'
  - 'the_silver_searcher'
  - '1password-cli'
  - 'jq'
  - 'yq'
  - 'pandoc'
  - 'htop'
  - 'just'
  - 'clang-format'
  - 'openjdk'
  - 'cowsay'
  - 'rlwrap'
casks:
  - 'cmake'
